### PR TITLE
Integrate upstream changes

### PR DESCRIPTION
**Pull request by MarkusTiede**
Shall we integrate these upstream changes?

### CODE REVIEW

**Comment by MarkusTiede** [comment]
Shall we also rename the repository accordingly from "module-eoss-ospo101" to "module-eoss-ospo-career-path"?

**Comment by MarkusTiede** [comment]
In my opinion we should wait until at least the [upstream errors are resolved](https://github.com/todogroup/ospo-career-path/issues/52#issuecomment-1311542325).

**Comment by yvo2** [comment]
👎🏼❌

**Comment by Tylyty** [comment]
👎 ❌

**Comment by Vujoa1** [comment]
👎🏼❌

**Comment by tropias** [comment]
👎🏼❌

**Comment by joelrohrbach** [comment]
👎 ❌

**Comment by gorbunov8** [comment]
👎 ❌

**Comment by celinestadelmann** [comment]
👎 ❌

**Comment by schor9** [comment]
👎🏼❌

**Comment by RuthuV96** [comment]
👍✅

**Comment by ronkaraqa** [comment]
👎 ❌

**Comment by Larsibaer** [comment]
👎🏼❌

**Comment by Saruhan99** [comment]
👎🏼❌

**Comment by abishanaru** [comment]
👎🏼❌

**Comment by eribeeri** [comment]
👎 ❌

**Comment by josuareich** [comment]
👎🏼❌

**Comment by SandroHertig** [comment]
👎🏼❌

**Comment by 98petra** [comment]
👎 ❌

**Comment by gilluuu** [comment]
👎 ❌

**Comment by Gitimur** [comment]
👎 ❌

**Comment by Simi2394** [comment]
👎 ❌

**Comment by yaeltnz** [comment]
👎 ❌

**Comment by Schil6** [comment]
👎🏼❌

**Comment by DarioK98** [comment]
👎🏼❌

**Comment by dhamzic1** [comment]
👎🏼❌

**Comment by NeromeSiva** [comment]
👎 ❌

**Comment by LarissaMargherita** [comment]
👎 ❌

**Comment by Saruhan99** [comment]
👎 ❌

**Pull request closed without merging**
